Add controllers
SergeyGray/java-shareit pull request #1
Opened 2022-12-16 21:07 UTC by SergeyGray

Выполнены все требования 13 Спринта

2022-12-17 04:17 UTC, sergeymamonov requested changes
userDto - неверное наименование пакета. Для имен пакетов используется snake_case.

2022-12-17 04:17 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public Item(int id, String name, String description, Boolean available, Integer owner, ItemRequest request) {
Попробуйте @AllArgsConstructor

2022-12-17 04:17 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/User.java
> +    public User(int id, String name, String email) {
Попробуйте @AllArgsConstructor

2022-12-17 04:17 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +            return;
Я бы кинул ошибку, в такой ситуации. Ведь мы же ограничиваем в сущности это поле, что оно не должно быть пустым.

2022-12-17 12:48 UTC, SergeyGray commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +            return;
Валидация Email на null происходит при создании юзера, но при обновлении поле Email может быть пустым - например, если изменяется только имя пользователя, то поле email будет null

2022-12-17 12:48 UTC, SergeyGray commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +            return;
Если будет проброс исключения тут, то не пройдут тесты

2022-12-18 09:18 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +            return;
Я бы попробовал сделать так: чтобы в этот метод гарантированно приходил юзер с почтой, либо от обновленных данных, либо из обновляемого. Но если будет почта от обновляемого, то запрос в хранилище найдет уже сохраненного пользователя, поэтому нужно будет сравнить по id. Чтобы нельзя было бы изменить пользователя и присвоить ему почту, на которую уже заведен другой пользователь. Но можете не заморачиваться и оставить как есть.

2022-12-18 09:19 UTC, sergeymamonov approved these changes

2023-01-18 12:58 UTC, merged