added requests,pageable,tests
SergeyGray/java-shareit pull request #3
Opened 2023-02-19 15:10 UTC by SergeyGray

Добавлена функциональность согласно 15 спринту - запросы вещей, пагинация и покрытие тестами приложения.

2023-02-20 09:43 UTC, sergeymamonov requested changes

2023-02-20 09:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>          try {
Такую проверку лучше сделать в сервисе.

2023-02-20 09:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                   @RequestParam(defaultValue = "0") Integer from,
А если клиент передаст отрицательное число?

2023-02-20 09:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImp.java
> +        } catch (Exception e) {
Какой метод дает в блоке try может кинуть исключение Exception? Пример, отвалилась сеть в момент запроса. Драйвер кинул исключение об ошибке сети, дальше ошибка преобразовалась в ItemStorageException("Запрос на вещь не найден"), но при это вещь есть в БД.

2023-02-20 19:37 UTC, SergeyGray commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                   @RequestParam(defaultValue = "0") Integer from,
Если клиент передаст отрицательное число то контроллер вернёт 400 код
Error handler обработает его как внутреннюю ошибку сервера - тесты на отрицательные число есть в  коллекции Postman

2023-02-20 20:20 UTC, SergeyGray commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>          try {
Почему лучше делать данную проверку в сервисе? Проходит валидация параметра передаваемого в контроллер - простейшие валидации не связанные с бизнес логикой как я понимаю допустимо проводить в контроллере.

2023-02-21 09:05 UTC, sergeymamonov approved these changes

2023-02-21 09:05 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>          try {
Пример, завтра добавится взаимодействие через брокер сообщений, например Кафка. Там тоже будет приходить сообщение, включающее статус. И точно такую же валидацию придется сделать и в листенере сообщений для топика Кафки. И получается что один и тот же код будет в двух местах. А если валидацию сделать в сервисе, то код будет только в одном месте.

2023-02-21 09:05 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                   @RequestParam(defaultValue = "0") Integer from,
Не вижу, чтобы могло указать контроллеру, что нельзя принимать отрицательное число для from и size. Можете подсказать?

2023-02-21 09:05 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImp.java
> +            return findItemsForRequests(itemRequestRepository.findById(requestId)
Может ли itemRequestRepository.findById(requestId) вернуть null?

2023-03-07 11:15 UTC, merged